Enhance Code Quality with Ruff, Black, and Pre-commit (#456)
* add: linter, formatter for github actions

* add: CONTRIBUTING.md

* add: pre-commit config and pre-commit rule

* fix: auto-fix with ruff

* fix: E401 Multiple imports on one line

* fix: E999 SyntaxError: Unexpected token 'json'

* fix: F821 Undefined name `unicode` by removing python2 compatibility

* fix: F811 Redefinition of unused `gtid` from line 3

* fix: E721 Do not compare types, use `isinstance()`

* fix: E721 Do not compare types, use `isinstance()`

* fix: F811 Redefinition of unused `TestMariadbBinlogStreamReader` from line 1012 by rename into TestMariadbBinlogStreamReader2

* fix: import json

* fix: fromtimestamp into utcfromtimestamp

* fix: apply black formatter

* fix: test that doesn't work

* fix: remove actions dependencies

* fix: E712

* fix: apply black

* fix: apply black

* fix: remove duplicated if-statement

* fix: indent for if-statement